/**
 * Types for Simulated Machines
 */

// Field types
export type FieldType = 'string' | 'number' | 'integer' | 'boolean';

// Machine status
export type MachineStatus = 'draft' | 'running';

/**
 * Field definition for a machine's payload
 */
export interface FieldDefinition {
  name: string;
  type: FieldType;
  formula?: string;
  static_value?: unknown;
  description?: string;
  min_value?: number;
  max_value?: number;
}

/**
 * Topic definition for multi-topic machines
 */
export interface TopicDefinition {
  topic_path: string;
  fields: FieldDefinition[];
}

/**
 * Complete machine definition
 */
export interface MachineDefinition {
  id?: string;
  name: string;
  description?: string;
  machine_type?: string;
  // Single topic (backward compat)
  topic_path?: string;
  schema_proposal_id?: string;
  fields: FieldDefinition[];
  // Multi-topic support
  topics?: TopicDefinition[];
  publish_interval_ms: number;
  status: MachineStatus;
  image_base64?: string;
  created_at?: string;
  created_by?: string;
  approved_at?: string;
  last_published_at?: string;
  // Similarity context (stored during creation for detail page visualization)
  similarity_results?: SimilarResult[];
  // SparkMES integration
  sparkmes_enabled?: boolean;
  sparkmes?: SparkMESStructure;
  // CESMII SM Profile
  smprofile?: SMProfile;
}

/**
 * A topic fetched from the knowledge graph for LLM context
 */
export interface ContextTopic {
  topic_path: string;
  field_names: string[];
  payload_preview: string;
}

/**
 * SparkMES tag structure for MES integration
 */
export interface SparkMESTag {
  name: string;
  tagType: 'AtomicTag' | 'Folder' | 'UdtInstance';
  value?: unknown;
  tags?: SparkMESTag[];
}

/**
 * SparkMES parameter definition
 */
export interface SparkMESParameter {
  dataType: string;
  value: unknown;
}

/**
 * Complete SparkMES structure generated by LLM
 */
export interface SparkMESStructure {
  name: string;
  typeId: string;
  parameters: Record<string, SparkMESParameter>;
  tagType: string;
  tags: SparkMESTag[];
}

/**
 * CESMII SM Profile - OPC UA Machine Identification
 */
export interface SMProfile {
  $namespace: string;
  manufacturer: string;
  serialNumber: string;
  productInstanceUri: string;
  manufacturerUri?: string;
  model?: string;
  productCode?: string;
  hardwareRevision?: string;
  softwareRevision?: string;
  deviceClass?: string;
  yearOfConstruction?: number;
  monthOfConstruction?: number;
  initialOperationDate?: string;
  assetId?: string;
  componentName?: string;
  location?: string;
}

/**
 * LLM-generated machine response
 */
export interface GeneratedMachineResponse {
  machine_type: string;
  suggested_name: string;
  description?: string;
  topic_path?: string;  // Set during Connect flow via similarity search
  fields: FieldDefinition[];
  publish_interval_ms: number;
  rationale?: string;
  context_topics?: ContextTopic[];  // Topics used for generation context
  sparkmes?: SparkMESStructure;  // SparkMES tag structure from LLM
  smprofile?: SMProfile;  // CESMII SM Profile
}

/**
 * A single similar schema/message result
 */
export interface SimilarSchemaResult {
  topic_path: string;
  similarity: number;
  field_names: string[];
  proposal_id?: string;
  proposal_name?: string;
}

/**
 * Schema suggestion response
 */
export interface SchemaSuggestionResponse {
  suggested_fields: FieldDefinition[];
  based_on: 'similar_schema' | 'original' | 'no_match';
  similar_results: SimilarSchemaResult[];  // Top 20 similar results
  overall_confidence: number;  // 0-1 confidence score
  confidence: 'high' | 'medium' | 'low';
}

/**
 * Formula suggestion for a field
 */
export interface FieldFormulaSuggestion {
  field_name: string;
  field_type: string;
  formula?: string;  // For dynamic fields
  static_value?: string;  // For static fields
  is_static: boolean;
  rationale: string;
  expected_min?: number;
  expected_max?: number;
}

/**
 * Context from a similar topic for formula generation
 */
export interface SimilarTopicContext {
  topic_path: string;
  similarity: number;
  field_names: string[];
  historical_payloads?: Record<string, unknown>[];
  source_field?: string;
}

/**
 * Formula suggestions response
 */
export interface FormulaSuggestionResponse {
  suggestions: FieldFormulaSuggestion[];
  based_on: 'historical_analysis' | 'field_ranges' | 'default';
}

/**
 * Interval suggestion response
 */
export interface IntervalSuggestionResponse {
  suggested_interval_ms: number;
  min_interval_ms: number;
  max_interval_ms: number;
  based_on: 'similar_topics' | 'default';
  sample_count: number;
}

/**
 * A suggested topic path
 */
export interface SuggestedTopic {
  topic_path: string;
  similarity: number;
  field_names: string[];
}

/**
 * Topic suggestion response
 */
export interface TopicSuggestionResponse {
  suggested_topic: string | null;
  similar_topics: SuggestedTopic[];
  confidence: 'high' | 'medium' | 'low';
}

/**
 * Historical payload from a topic
 */
export interface HistoricalPayload {
  payload: Record<string, unknown>;
  timestamp?: string;
}

/**
 * Similar result with historical payloads (for unified suggestion)
 */
export interface SimilarResult {
  topic_path: string;
  similarity: number;  // Weighted: 60% topic semantic + 40% field Jaccard
  field_names: string[];
  historical_payloads: HistoricalPayload[];  // Last 10 payloads for top 10 results
}

/**
 * A suggested topic with its fields (for multi-topic machines)
 */
export interface TopicSuggestion {
  topic_path: string;
  fields: FieldDefinition[];
  source_field?: string;  // Which original field this topic represents
}

/**
 * Unified topic + schema suggestion response
 */
export interface UnifiedSuggestionResponse {
  // Single topic suggestion (backward compat)
  suggested_topic: string | null;
  suggested_fields: FieldDefinition[];

  // Multi-topic suggestions (when split pattern detected)
  suggested_topics: TopicSuggestion[];

  // Pattern detected from similar topics
  topic_pattern: 'single' | 'split_by_metric';

  // Context for UI display
  similar_results: SimilarResult[];
  confidence: 'high' | 'medium' | 'low';
  overall_similarity: number;
}

/**
 * Machine status response
 */
export interface MachineStatusResponse {
  id: string;
  name: string;
  status: MachineStatus;
  is_running: boolean;
  last_published_at?: string;
  messages_published: number;
}

// API Request types

export interface GenerateRandomRequest {
  machine_type_hint?: string;
}

export interface GeneratePromptedRequest {
  prompt: string;
  conversation_history?: Array<{ role: string; content: string }>;
}

export interface CreateMachineRequest {
  name: string;
  description?: string;
  machine_type?: string;
  // Single topic (backward compat)
  topic_path?: string;
  schema_proposal_id?: string;
  fields?: FieldDefinition[];
  // Multi-topic support
  topics?: TopicDefinition[];
  publish_interval_ms: number;
  image_base64?: string;
  // Similarity context from creation
  similarity_results?: SimilarResult[];
  // SparkMES integration
  sparkmes_enabled?: boolean;
  sparkmes?: SparkMESStructure;
  // CESMII SM Profile
  smprofile?: SMProfile;
  // Creator
  created_by?: string;
}

export interface MachineListResponse {
  machines: MachineDefinition[];
  total: number;
}

// Ladder Logic Types

export interface LadderElement {
  type: 'contact' | 'inverted_contact' | 'output' | 'analog_output' | 'set_coil' | 'reset_coil' | 'timer' | 'counter';
  name: string;
  preset_ms?: number;
  timer_type?: 'TON' | 'TOFF';
  preset?: number;
  counter_type?: 'CTU' | 'CTD';
  // For analog_output
  min_value?: number;
  max_value?: number;
  step?: number;
}

export interface LadderRung {
  description: string;
  elements: LadderElement[];
}

export interface LadderProgram {
  rungs: LadderRung[];
}

export interface IOMapping {
  inputs: string[];
  outputs: string[];
  internal: string[];
}

export interface GenerateLadderRequest {
  machine_type: string;
  fields: FieldDefinition[];
  description?: string;
}

export interface GenerateLadderResponse {
  ladder_program: LadderProgram;
  io_mapping: IOMapping;
  rationale?: string;
}

/**
 * Stored ladder logic data for a machine
 */
export interface LadderLogicData {
  rungs: LadderRung[];
  io_mapping: IOMapping;
  rationale?: string;
  created_at?: string;
}
