"""LLM prompt templates for machine generation."""

from .random_machine import (
    RANDOM_MACHINE_SYSTEM_PROMPT,
    RANDOM_MACHINE_USER_PROMPT,
    CONTEXT_AWARE_RANDOM_SYSTEM_PROMPT,
    CONTEXT_AWARE_RANDOM_USER_PROMPT,
)
from .prompted_machine import PROMPTED_MACHINE_SYSTEM_PROMPT
from .formula_suggestion import FORMULA_SUGGESTION_SYSTEM_PROMPT, FORMULA_SUGGESTION_USER_PROMPT
from .topic_suggestion import TOPIC_SUGGESTION_SYSTEM_PROMPT, TOPIC_SUGGESTION_USER_PROMPT
from .unified_suggestion import UNIFIED_SUGGESTION_SYSTEM_PROMPT, UNIFIED_SUGGESTION_USER_PROMPT
from .ladder_generation import LADDER_GENERATION_SYSTEM_PROMPT, LADDER_GENERATION_USER_PROMPT
from .smprofile_generation import SMPROFILE_GENERATION_SYSTEM_PROMPT, SMPROFILE_GENERATION_USER_PROMPT
from .machine_chat import MACHINE_CHAT_SYSTEM_PROMPT, build_machine_chat_user_prompt
from .knowledge_base_chat import KB_CHAT_SYSTEM_PROMPT, build_kb_user_prompt

__all__ = [
    "RANDOM_MACHINE_SYSTEM_PROMPT",
    "RANDOM_MACHINE_USER_PROMPT",
    "CONTEXT_AWARE_RANDOM_SYSTEM_PROMPT",
    "CONTEXT_AWARE_RANDOM_USER_PROMPT",
    "PROMPTED_MACHINE_SYSTEM_PROMPT",
    "FORMULA_SUGGESTION_SYSTEM_PROMPT",
    "FORMULA_SUGGESTION_USER_PROMPT",
    "TOPIC_SUGGESTION_SYSTEM_PROMPT",
    "TOPIC_SUGGESTION_USER_PROMPT",
    "UNIFIED_SUGGESTION_SYSTEM_PROMPT",
    "UNIFIED_SUGGESTION_USER_PROMPT",
    "LADDER_GENERATION_SYSTEM_PROMPT",
    "LADDER_GENERATION_USER_PROMPT",
    "SMPROFILE_GENERATION_SYSTEM_PROMPT",
    "SMPROFILE_GENERATION_USER_PROMPT",
    "MACHINE_CHAT_SYSTEM_PROMPT",
    "build_machine_chat_user_prompt",
    "KB_CHAT_SYSTEM_PROMPT",
    "build_kb_user_prompt",
]
